import * as THREE from '../PlanetForge/vendor/three/three.module.js';
import {FBXLoader} from '../PlanetForge/vendor/three/addons/loaders/FBXLoader.js';
const $=id=>document.getElementById(id),state={source:null,lods:[],selected:0,name:'model',orbit:{x:.3,y:.65},zoom:1};
let toastTimer;function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2400)}
const renderer=new THREE.WebGLRenderer({canvas:$('view'),antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.01,100);scene.add(new THREE.HemisphereLight(0xeaf3ff,0x35322d,2.2));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(4,6,5);scene.add(key);let display=null;
function render(){const r=$('view').getBoundingClientRect();renderer.setSize(r.width|0,r.height|0,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();const d=4/state.zoom,cx=Math.cos(state.orbit.x),sx=Math.sin(state.orbit.x);camera.position.set(Math.sin(state.orbit.y)*cx*d,-sx*d,Math.cos(state.orbit.y)*cx*d);camera.lookAt(0,0,0);renderer.render(scene,camera)}
function showLOD(i){state.selected=i;const m=state.lods[i]||state.source;if(!m)return;if(display){display.geometry.dispose();scene.remove(display)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(m.pos,3));if(m.uv?.length)g.setAttribute('uv',new THREE.Float32BufferAttribute(m.uv,2));g.computeVertexNormals();display=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0xc8d0d5,roughness:.62,metalness:.08,side:THREE.DoubleSide}));scene.add(display);document.querySelectorAll('.tab').forEach((b,j)=>b.classList.toggle('active',j===i));render()}
function normalize(m){let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<m.pos.length;i+=3)for(let k=0;k<3;k++){min[k]=Math.min(min[k],m.pos[i+k]);max[k]=Math.max(max[k],m.pos[i+k])}const c=min.map((v,k)=>(v+max[k])/2),s=2/(Math.max(...max.map((v,k)=>v-min[k]))||1);for(let i=0;i<m.pos.length;i+=3)for(let k=0;k<3;k++)m.pos[i+k]=(m.pos[i+k]-c[k])*s;return m}
function parseOBJ(text){const v=[],vt=[],pos=[],uv=[];for(const line of text.split(/\r?\n/)){const p=line.trim().split(/\s+/);if(p[0]==='v')v.push([+p[1],+p[2],+p[3]]);else if(p[0]==='vt')vt.push([+p[1],+p[2]]);else if(p[0]==='f'){const q=p.slice(1).map(x=>x.split('/').map(Number));for(let j=1;j<q.length-1;j++)for(const x of [q[0],q[j],q[j+1]]){const vi=x[0]<0?v.length+x[0]:x[0]-1,ti=x[1]?(x[1]<0?vt.length+x[1]:x[1]-1):-1;pos.push(...v[vi]);uv.push(...(vt[ti]||[0,0]));}}}if(!pos.length)throw Error('No OBJ triangles found');return normalize({pos,uv})}
async function parseGLTF(file,files){let j,bin;if(/\.glb$/i.test(file.name)){const a=await file.arrayBuffer(),d=new DataView(a);if(d.getUint32(0,true)!==0x46546c67)throw Error('Invalid GLB');for(let o=12;o<a.byteLength;){const n=d.getUint32(o,true),t=d.getUint32(o+4,true),c=a.slice(o+8,o+8+n);if(t===0x4e4f534a)j=JSON.parse(new TextDecoder().decode(c));else if(t===0x004e4942)bin=c;o+=8+n}}else j=JSON.parse(await file.text());const bufs=[];for(const b of j.buffers||[]){if(!b.uri)bufs.push(bin);else if(b.uri.startsWith('data:')){const s=atob(b.uri.split(',')[1]),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);bufs.push(a.buffer)}else{const f=files.find(x=>x.name===decodeURIComponent(b.uri).split('/').pop());if(!f)throw Error(`Also select ${b.uri}`);bufs.push(await f.arrayBuffer())}}const C={5120:Int8Array,5121:Uint8Array,5122:Int16Array,5123:Uint16Array,5125:Uint32Array,5126:Float32Array},N={SCALAR:1,VEC2:2,VEC3:3,VEC4:4},G={5120:'getInt8',5121:'getUint8',5122:'getInt16',5123:'getUint16',5125:'getUint32',5126:'getFloat32'};const read=i=>{const a=j.accessors[i],b=j.bufferViews[a.bufferView],n=N[a.type],z=C[a.componentType].BYTES_PER_ELEMENT,str=b.byteStride||n*z,d=new DataView(bufs[b.buffer]),base=(b.byteOffset||0)+(a.byteOffset||0),out=[];for(let x=0;x<a.count;x++){const row=[];for(let k=0;k<n;k++)row.push(d[G[a.componentType]](base+x*str+k*z,true));out.push(n===1?row[0]:row)}return out};const pos=[],uv=[];for(const mesh of j.meshes||[])for(const p of mesh.primitives||[]){if((p.mode??4)!==4)continue;const ps=read(p.attributes.POSITION),us=p.attributes.TEXCOORD_0!==undefined?read(p.attributes.TEXCOORD_0):null,ix=p.indices!==undefined?read(p.indices):ps.map((_,i)=>i);for(const n of ix){pos.push(...ps[n].slice(0,3));uv.push(...(us?.[n]?.slice(0,2)||[0,0]))}}if(!pos.length)throw Error('No glTF triangles found');return normalize({pos,uv})}
async function parseFBX(file){const root=new FBXLoader().parse(await file.arrayBuffer(),'');root.updateMatrixWorld(true);const pos=[],uv=[];root.traverse(o=>{if(!o.isMesh||!o.geometry?.attributes.position)return;const g=o.geometry.clone();g.applyMatrix4(o.matrixWorld);const p=g.attributes.position,u=g.attributes.uv,ix=g.index?g.index.array:Array.from({length:p.count},(_,i)=>i);for(const n of ix){pos.push(p.getX(n),p.getY(n),p.getZ(n));uv.push(u?u.getX(n):0,u?u.getY(n):0)}});if(!pos.length)throw Error('No FBX mesh found');return normalize({pos,uv})}
function clustered(src,cell,protect){const sums=new Map(),ids=[],p=src.pos,u=src.uv;for(let i=0;i<p.length/3;i++){const x=p[i*3],y=p[i*3+1],z=p[i*3+2],us=u[i*2]||0,vs=u[i*2+1]||0,key=`${Math.floor(x/cell)},${Math.floor(y/cell)},${Math.floor(z/cell)}`+(protect?`/${Math.floor(us*24)},${Math.floor(vs*24)}`:'');let q=sums.get(key);if(!q){q={p:[0,0,0],u:[0,0],n:0,id:sums.size};sums.set(key,q)}q.p[0]+=x;q.p[1]+=y;q.p[2]+=z;q.u[0]+=us;q.u[1]+=vs;q.n++;ids.push(q.id)}const verts=[...sums.values()].map(q=>({p:q.p.map(x=>x/q.n),u:q.u.map(x=>x/q.n)})),pos=[],uv=[];for(let i=0;i<ids.length;i+=3){if(ids[i]===ids[i+1]||ids[i]===ids[i+2]||ids[i+1]===ids[i+2])continue;for(const id of [ids[i],ids[i+1],ids[i+2]]){pos.push(...verts[id].p);uv.push(...verts[id].u)}}return {pos,uv}}
function simplify(src,ratio,protect){const target=Math.max(4,Math.round(src.pos.length/9*ratio));let lo=1e-5,hi=2,best=src,bestD=Infinity;for(let n=0;n<18;n++){const c=(lo+hi)/2,m=clustered(src,c,protect),tris=m.pos.length/9,d=Math.abs(tris-target);if(d<bestD&&tris>0){best=m;bestD=d}if(tris>target)lo=c;else hi=c}return best}
function ratiosUI(){const n=+$('levelCount').value,box=$('ratios');box.innerHTML='';for(let i=0;i<n;i++){const val=i?Math.max(3,Math.round(100*Math.pow(.5,i))):100;box.insertAdjacentHTML('beforeend',`<label class="ratio"><b>LOD${i}</b><input type="range" min="2" max="100" value="${val}" ${i?'':'disabled'}><output>${val}%</output></label>`)}box.querySelectorAll('input').forEach(x=>x.oninput=()=>x.nextElementSibling.value=x.value+'%')}
$('levelCount').onchange=ratiosUI;ratiosUI();$('pick').onclick=()=>$('files').click();$('files').onchange=async e=>{const files=[...e.target.files],f=files.find(x=>/\.(obj|gltf|glb|fbx)$/i.test(x.name));if(!f)return;try{$('status').textContent='Parsing model…';state.name=f.name.replace(/\.[^.]+$/,'').replace(/[^\w-]+/g,'_');state.source=/\.obj$/i.test(f.name)?parseOBJ(await f.text()):/\.fbx$/i.test(f.name)?await parseFBX(f):await parseGLTF(f,files);state.lods=[state.source];$('sourceStats').textContent=`${f.name} · ${(state.source.pos.length/9).toLocaleString()} triangles`;$('generate').disabled=false;showLOD(0);$('status').textContent='Source ready'}catch(err){toast(err.message);$('status').textContent='Import failed'}e.target.value=''};
$('generate').onclick=()=>{if(!state.source)return;$('status').textContent='Generating…';requestAnimationFrame(()=>{const rs=[...document.querySelectorAll('.ratio input')].map(x=>+x.value/100);state.lods=rs.map((r,i)=>i? simplify(state.source,r,$('preserveUV').checked):state.source);buildResults();showLOD(0);$('exportFiles').disabled=$('exportUnity').disabled=false;$('status').textContent=`${state.lods.length} levels generated`;toast('LOD meshes ready')})};
function buildResults(){const tabs=$('lodTabs'),res=$('results');tabs.innerHTML=res.innerHTML='';state.lods.forEach((m,i)=>{const b=document.createElement('button');b.className='tab';b.textContent=`LOD${i}`;b.onclick=()=>showLOD(i);tabs.append(b);res.insertAdjacentHTML('beforeend',`<div class="result"><b>LOD${i}</b>${(m.pos.length/9).toLocaleString()} triangles<br>${Math.round(m.pos.length/state.source.pos.length*100)}% of source</div>`)})}
let drag=null;const cv=$('view');cv.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};cv.setPointerCapture(e.pointerId)};cv.onpointermove=e=>{if(!drag)return;state.orbit.y+=(e.clientX-drag.x)*.01;state.orbit.x=Math.max(-1.45,Math.min(1.45,state.orbit.x+(e.clientY-drag.y)*.01));drag={x:e.clientX,y:e.clientY};render()};cv.onpointerup=cv.onpointercancel=()=>drag=null;cv.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.45,Math.min(3,state.zoom*(e.deltaY<0?1.1:.9)));render()};addEventListener('resize',render);
function objText(m,name){let s=`# PlanetLOD\no ${name}\n`;for(let i=0;i<m.pos.length;i+=3)s+=`v ${m.pos[i]} ${m.pos[i+1]} ${m.pos[i+2]}\n`;for(let i=0;i<m.uv.length;i+=2)s+=`vt ${m.uv[i]} ${m.uv[i+1]}\n`;for(let i=0;i<m.pos.length/3;i+=3)s+=`f ${i+1}/${i+1} ${i+2}/${i+2} ${i+3}/${i+3}\n`;return s}
function glb(m){const p=new Float32Array(m.pos),u=new Float32Array(m.uv),bin=new Uint8Array(p.byteLength+u.byteLength);bin.set(new Uint8Array(p.buffer));bin.set(new Uint8Array(u.buffer),p.byteLength);const j={asset:{version:'2.0',generator:'PlanetLOD'},buffers:[{byteLength:bin.length}],bufferViews:[{buffer:0,byteOffset:0,byteLength:p.byteLength,target:34962},{buffer:0,byteOffset:p.byteLength,byteLength:u.byteLength,target:34962}],accessors:[{bufferView:0,componentType:5126,count:p.length/3,type:'VEC3'},{bufferView:1,componentType:5126,count:u.length/2,type:'VEC2'}],meshes:[{primitives:[{attributes:{POSITION:0,TEXCOORD_0:1},mode:4}]}],nodes:[{mesh:0}],scenes:[{nodes:[0]}],scene:0};let js=new TextEncoder().encode(JSON.stringify(j)),jp=(4-js.length%4)%4,bp=(4-bin.length%4)%4,total=12+8+js.length+jp+8+bin.length+bp,a=new ArrayBuffer(total),d=new DataView(a),o=20,x=new Uint8Array(a);d.setUint32(0,0x46546c67,true);d.setUint32(4,2,true);d.setUint32(8,total,true);d.setUint32(12,js.length+jp,true);d.setUint32(16,0x4e4f534a,true);x.set(js,o);x.fill(32,o+js.length,o+js.length+jp);o+=js.length+jp;d.setUint32(o,bin.length+bp,true);d.setUint32(o+4,0x004e4942,true);x.set(bin,o+8);return new Blob([a],{type:'model/gltf-binary'})}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
$('exportFiles').onclick=()=>state.lods.forEach((m,i)=>setTimeout(()=>download($('format').value==='glb'?glb(m):new Blob([objText(m,`${state.name}_LOD${i}`)],{type:'text/plain'}),`${state.name}_LOD${i}.${$('format').value}`),i*250));
const guid=()=>crypto.randomUUID().replaceAll('-','');
function meta(g){return `fileFormatVersion: 2\nguid: ${g}\nModelImporter:\n  serializedVersion: 22200\n  globalScale: 1\n  meshCompression: 0\n  addCollider: 0\n  importMaterials: 0\n  useFileScale: 1\n`}
function prefab(meshGuids,prefabGuid){let out='%YAML 1.1\n%TAG !u! tag:unity3d.com,2011:\n',children='',root=1000,tr=1001,lod=1002;out+=`--- !u!1 &${root}\nGameObject:\n  m_ObjectHideFlags: 0\n  m_Component:\n  - component: {fileID: ${tr}}\n  - component: {fileID: ${lod}}\n  m_Layer: 0\n  m_Name: ${state.name}_LODGroup\n--- !u!4 &${tr}\nTransform:\n  m_GameObject: {fileID: ${root}}\n  m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}\n  m_LocalPosition: {x: 0, y: 0, z: 0}\n  m_LocalScale: {x: 1, y: 1, z: 1}\n  m_Children:\n${meshGuids.map((_,i)=>`  - {fileID: ${2000+i*10+1}}`).join('\n')}\n  m_Father: {fileID: 0}\n--- !u!205 &${lod}\nLODGroup:\n  m_GameObject: {fileID: ${root}}\n  m_Enabled: 1\n  serializedVersion: 2\n  m_LODs:\n`;
meshGuids.forEach((g,i)=>{const go=2000+i*10,t=go+1,mf=go+2,mr=go+3,screen=i===meshGuids.length-1?.01:Math.max(.02,.6*Math.pow(.45,i));out+=`  - screenRelativeHeight: ${screen}\n    fadeTransitionWidth: 0\n    renderers:\n    - renderer: {fileID: ${mr}}\n`;children+=`--- !u!1 &${go}\nGameObject:\n  m_Component:\n  - component: {fileID: ${t}}\n  - component: {fileID: ${mf}}\n  - component: {fileID: ${mr}}\n  m_Layer: 0\n  m_Name: LOD${i}\n--- !u!4 &${t}\nTransform:\n  m_GameObject: {fileID: ${go}}\n  m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}\n  m_LocalPosition: {x: 0, y: 0, z: 0}\n  m_LocalScale: {x: 1, y: 1, z: 1}\n  m_Children: []\n  m_Father: {fileID: ${tr}}\n--- !u!33 &${mf}\nMeshFilter:\n  m_GameObject: {fileID: ${go}}\n  m_Mesh: {fileID: 4300000, guid: ${g}, type: 3}\n--- !u!23 &${mr}\nMeshRenderer:\n  m_GameObject: {fileID: ${go}}\n  m_Enabled: 1\n  m_Materials:\n  - {fileID: 10303, guid: 0000000000000000f000000000000000, type: 0}\n`});out+=`  m_AnimateCrossFading: 0\n  m_LastLODIsBillboard: 0\n  m_Size: 2\n  m_LocalReferencePoint: {x: 0, y: 0, z: 0}\n`;return out+children}
function tar(entries){const enc=new TextEncoder(),parts=[];for(const [name,data] of entries){const body=typeof data==='string'?enc.encode(data):data,head=new Uint8Array(512),put=(s,o,n)=>head.set(enc.encode(s).slice(0,n),o),oct=(v,n)=>(v.toString(8).padStart(n-1,'0')+'\0');put(name,0,100);put('0000777\0',100,8);put('0000000\0',108,8);put('0000000\0',116,8);put(oct(body.length,12),124,12);put(oct(Math.floor(Date.now()/1000),12),136,12);head.fill(32,148,156);head[156]=48;put('ustar\0',257,6);put('00',263,2);let sum=head.reduce((a,b)=>a+b,0);put(oct(sum,8),148,8);parts.push(head,body,new Uint8Array((512-body.length%512)%512))}parts.push(new Uint8Array(1024));return new Blob(parts)}
async function gzip(blob){if(!window.CompressionStream)throw Error('This browser cannot create gzip archives');const stream=blob.stream().pipeThrough(new CompressionStream('gzip'));return new Blob([await new Response(stream).arrayBuffer()],{type:'application/gzip'})}
$('exportUnity').onclick=async()=>{try{$('status').textContent='Building Unity package…';const entries=[],gs=state.lods.map(guid),pg=guid(),base=`Assets/PlanetLOD/${state.name}`;state.lods.forEach((m,i)=>{const path=`${base}/${state.name}_LOD${i}.obj`,g=gs[i];entries.push([`${g}/asset`,objText(m,`${state.name}_LOD${i}`)],[`${g}/asset.meta`,meta(g)],[`${g}/pathname`,path])});const pp=`${base}/${state.name}_LODGroup.prefab`;entries.push([`${pg}/asset`,prefab(gs,pg)],[`${pg}/asset.meta`,`fileFormatVersion: 2\nguid: ${pg}\nPrefabImporter:\n  externalObjects: {}\n  userData: \n  assetBundleName: \n  assetBundleVariant: \n`],[`${pg}/pathname`,pp]);download(await gzip(tar(entries)),`${state.name}-lods.unitypackage`);$('status').textContent='Unity package ready';toast('Unity LODGroup package exported')}catch(e){toast(e.message);$('status').textContent='Package export failed'}};
render();
