(function(){
  'use strict';
  const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d',{alpha:true});
  const PRESETS=[
    ['Custom size',0,0,'Enter any output dimensions.'],
    ['Square · universal',1080,1080,'Useful for profile pictures and square posts.'],
    ['Discord · avatar',512,512,'Square source; Discord displays it as a circle.'],['Discord · server icon',512,512,'Square server or community icon.'],['Discord · emoji',128,128,'Compact custom emoji canvas.'],['Discord · server banner',960,540,'16:9 server banner.'],
    ['Instagram · square post',1080,1080,'1:1 feed post.'],['Instagram · portrait post',1080,1350,'4:5 portrait feed post.'],['Instagram · story / reel',1080,1920,'9:16 full-screen vertical.'],['Instagram · profile',320,320,'Square source; displayed as a circle.'],
    ['YouTube · thumbnail',1280,720,'16:9 video thumbnail.'],['YouTube · channel banner',2560,1440,'Keep important content centered for device-safe cropping.'],['YouTube · profile',800,800,'Square channel profile image.'],
    ['X · post landscape',1600,900,'Common 16:9 post image.'],['X · header',1500,500,'Wide profile header.'],['X · profile',400,400,'Square source; displayed as a circle.'],
    ['Facebook · post',1200,630,'Common landscape link/post image.'],['Facebook · cover',1640,624,'High-resolution page/profile cover ratio.'],['Facebook · profile',320,320,'Square profile source.'],
    ['LinkedIn · post',1200,627,'Landscape feed image.'],['LinkedIn · profile background',1584,396,'Recommended 4:1 profile cover.'],['LinkedIn · profile',400,400,'Square profile image.'],
    ['Twitch · profile',800,800,'Square channel avatar.'],['Twitch · offline banner',1920,1080,'16:9 offline screen.'],['Twitch · profile banner',1200,480,'Wide channel banner.'],
    ['TikTok · profile',200,200,'Square profile source.'],['TikTok · vertical video cover',1080,1920,'9:16 vertical cover canvas.'],
    ['Website · Open Graph',1200,630,'Social sharing preview.'],['Website · favicon',512,512,'Large square favicon source.'],['Website · hero 16:9',1920,1080,'Full HD web hero.'],
    ['Apple App Store · icon',1024,1024,'App Store icon source; do not pre-round corners.'],['Google Play · icon',512,512,'Play Store listing icon.'],['Google Play · feature graphic',1024,500,'Store listing feature banner.'],
    ['Wallpaper · Full HD',1920,1080,'16:9 desktop wallpaper.'],['Wallpaper · 4K',3840,2160,'4K UHD desktop wallpaper.']
  ];
  let items=[],active=-1,fit='cover',exportMode='lossy',locked=true,lockedRatio=1,rotation=0,flipX=1,flipY=1,view='after',blob=null,renderTimer=0,encodeTimer=0,frame=0,renderVersion=0;
  PRESETS.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p[0]+(p[1]?' · '+p[1]+'×'+p[2]:'');$('preset').appendChild(o);});$('preset').value='1';
  function human(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(2)+' MB';}
  function status(s,kind){$('status').textContent=s;$('status').className='status'+(kind?' '+kind:'');}
  function current(){return items[active]||null;}
  function loadFiles(files){[...files].filter(f=>f.type.startsWith('image/')).forEach(file=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{items.push({file,url,img,w:img.naturalWidth,h:img.naturalHeight});if(active<0)active=0;renderQueue();select(active);};img.onerror=()=>{URL.revokeObjectURL(url);status('Could not read '+file.name+'.','err');};img.src=url;});}
  function renderQueue(){$('queue').innerHTML='';items.forEach((it,i)=>{const b=document.createElement('button');b.className=i===active?'active':'';b.title=it.file.name;const im=document.createElement('img');im.src=it.url;im.alt='';b.appendChild(im);b.onclick=()=>select(i);$('queue').appendChild(b);});}
  function select(i){active=i;const it=current();if(!it)return;rotation=0;flipX=flipY=1;$('zoom').value=100;$('focus-x').value=$('focus-y').value=50;$('preview-name').textContent=it.file.name;$('source-info').textContent=it.w+' × '+it.h+' · '+human(it.file.size);$('empty').hidden=true;$('download').disabled=false;$('download-all').disabled=false;renderQueue();schedule();}
  function dims(it){let w=Math.max(1,Math.min(12000,+$('width').value||1)),h=Math.max(1,Math.min(12000,+$('height').value||1));it=it||current();if($('keep-size').checked&&it){const rotated=rotation%180!==0,sw=rotated?it.h:it.w,sh=rotated?it.w:it.h;if(w>sw||h>sh){const k=Math.min(sw/w,sh/h,1);w=Math.max(1,Math.round(w*k));h=Math.max(1,Math.round(h*k));}}return[w,h];}
  function rawDraw(target,it,w,h){target.width=w;target.height=h;const c=target.getContext('2d',{alpha:true});c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.clearRect(0,0,w,h);if(fit==='contain'){c.fillStyle=$('background').value;c.fillRect(0,0,w,h);}const turned=rotation%180!==0,iw=turned?it.h:it.w,ih=turned?it.w:it.h;let scale=fit==='stretch'?1:fit==='cover'?Math.max(w/iw,h/ih):Math.min(w/iw,h/ih);if(fit==='cover')scale*=+$('zoom').value/100;let dw=fit==='stretch'?w:iw*scale,dh=fit==='stretch'?h:ih*scale;const fx=+$('focus-x').value/100,fy=+$('focus-y').value/100,x=(w-dw)*fx,y=(h-dh)*fy;c.save();c.translate(x+dw/2,y+dh/2);c.scale(flipX,flipY);c.rotate(rotation*Math.PI/180);const rw=fit==='stretch'?(turned?dh:dw):(it.w*scale),rh=fit==='stretch'?(turned?dw:dh):(it.h*scale);c.drawImage(it.img,-rw/2,-rh/2,rw,rh);c.restore();}
  function recoverDetail(c,strength){if(!strength||c.width*c.height>24000000)return;const x=c.getContext('2d'),img=x.getImageData(0,0,c.width,c.height),src=new Uint8ClampedArray(img.data),d=img.data,w=c.width,h=c.height,a=strength/100*.42;for(let y=1;y<h-1;y++)for(let px=1;px<w-1;px++){const i=(y*w+px)*4;for(let k=0;k<3;k++){const lap=4*src[i+k]-src[i-4+k]-src[i+4+k]-src[i-w*4+k]-src[i+w*4+k];if(Math.abs(lap)>5)d[i+k]=src[i+k]+lap*a;}}x.putImageData(img,0,0);}
  function draw(target,it,fastPreview){const [w,h]=dims(it),turned=rotation%180!==0,iw=turned?it.h:it.w,ih=turned?it.w:it.h,upscale=!fastPreview&&$('super-resolution').checked&&Math.max(w/iw,h/ih)>1.08;if(!upscale){rawDraw(target,it,w,h);return;}const factor=Math.min(4,Math.max(1,w/iw,h/ih)),base=document.createElement('canvas'),bw=Math.max(1,Math.round(w/factor)),bh=Math.max(1,Math.round(h/factor));rawDraw(base,it,bw,bh);let source=base,cw=bw,ch=bh;while(cw<w||ch<h){const nw=Math.min(w,Math.max(cw+1,Math.round(cw*1.65))),nh=Math.min(h,Math.max(ch+1,Math.round(ch*1.65))),step=document.createElement('canvas');step.width=nw;step.height=nh;const sx=step.getContext('2d');sx.imageSmoothingEnabled=true;sx.imageSmoothingQuality='high';sx.drawImage(source,0,0,nw,nh);source=step;cw=nw;ch=nh;}target.width=w;target.height=h;target.getContext('2d').drawImage(source,0,0);recoverDetail(target,+$('detail').value);}
  function mime(){return exportMode==='lossless'?'image/png':$('format').value;}
  function ext(){return mime()==='image/jpeg'?'jpg':mime()==='image/webp'?'webp':'png';}
  function canvasBlob(c,type,q){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Your browser could not encode this image.')),type,q));}
  async function encode(c){const type=mime();if(type==='image/png')return canvasBlob(c,type);let q=+$('quality').value/100;if(!$('target-on').checked)return canvasBlob(c,type,q);const target=Math.max(5,+$('target-size').value||500)*1024;let lo=.05,hi=1,best=null;for(let i=0;i<8;i++){const mid=(lo+hi)/2,b=await canvasBlob(c,type,mid);if(b.size<=target){best=b;lo=mid;}else hi=mid;}return best||canvasBlob(c,type,.05);}
  async function render(previewOnly){const it=current(),version=++renderVersion;if(!it)return;try{if(view==='before'){canvas.width=it.w;canvas.height=it.h;ctx.clearRect(0,0,it.w,it.h);ctx.drawImage(it.img,0,0);$('result-dims').textContent='Original · '+it.w+' × '+it.h;$('result-size').textContent=human(it.file.size);$('saving').textContent='—';return;}draw(canvas,it,previewOnly);$('result-dims').textContent=canvas.width+' × '+canvas.height;if(previewOnly)return;blob=await encode(canvas);if(version!==renderVersion)return;$('result-size').textContent=human(blob.size)+' · '+ext().toUpperCase();const save=it.file.size-blob.size;$('saving').textContent=save>0?'↓ '+Math.round(save/it.file.size*100)+'% smaller':save<0?'↑ '+Math.round(-save/it.file.size*100)+'% larger':'same size';status('Preview ready.','ok');}catch(e){status(e.message,'err');}}
  function schedule(fast){clearTimeout(renderTimer);clearTimeout(encodeTimer);if(fast){cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>render(true));encodeTimer=setTimeout(()=>render(false),260);}else renderTimer=setTimeout(()=>render(false),80);}
  function filename(it,c){const base=it.file.name.replace(/\.[^.]+$/,'');return base+($('suffix-on').checked?'-'+c.width+'x'+c.height:'')+'.'+ext();}
  function saveBlob(b,name){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  async function download(){const it=current();if(!it)return;draw(canvas,it);const b=await encode(canvas);saveBlob(b,filename(it,canvas));status('Downloaded '+filename(it,canvas)+'.','ok');}
  async function downloadAll(){if(!items.length)return;status('Processing '+items.length+' images…');for(let i=0;i<items.length;i++){const c=document.createElement('canvas');draw(c,items[i]);const b=await encode(c);saveBlob(b,filename(items[i],c));await new Promise(r=>setTimeout(r,180));}status('Processed all '+items.length+' images. Your browser may ask to allow multiple downloads.','ok');}
  function preset(){const p=PRESETS[+$('preset').value];if(p[1]){$('width').value=p[1];$('height').value=p[2];lockedRatio=p[1]/p[2];}$('preset-note').textContent=p[3];schedule();}
  function setFit(v){fit=v;document.querySelectorAll('#fit button').forEach(b=>b.classList.toggle('active',b.dataset.fit===v));$('crop-controls').hidden=v!=='cover';document.querySelectorAll('.contain-opt').forEach(x=>x.hidden=v!=='contain');schedule();}
  function setMode(v){exportMode=v;document.querySelectorAll('#mode button').forEach(b=>b.classList.toggle('active',b.dataset.mode===v));document.querySelectorAll('.lossy-opt').forEach(x=>x.hidden=v!=='lossy');document.querySelector('.lossless-note').hidden=v!=='lossless';$('target-on').dispatchEvent(new Event('change'));schedule();}
  function dimensionChanged(which){if(locked){if(which==='w')$('height').value=Math.max(1,Math.round(+$('width').value/lockedRatio));else $('width').value=Math.max(1,Math.round(+$('height').value*lockedRatio));}$('preset').value=0;$('preset-note').textContent=PRESETS[0][3];schedule();}
  $('files').onchange=e=>{loadFiles(e.target.files);e.target.value='';};['dragenter','dragover'].forEach(n=>$('drop').addEventListener(n,e=>{e.preventDefault();$('drop').classList.add('over');}));['dragleave','drop'].forEach(n=>$('drop').addEventListener(n,e=>{e.preventDefault();$('drop').classList.remove('over');}));$('drop').addEventListener('drop',e=>loadFiles(e.dataTransfer.files));
  $('preset').onchange=preset;$('width').oninput=()=>dimensionChanged('w');$('height').oninput=()=>dimensionChanged('h');$('lock').onclick=()=>{locked=!locked;if(locked)lockedRatio=(+$('width').value||1)/(+$('height').value||1);$('lock').classList.toggle('active',locked);};document.querySelectorAll('#fit button').forEach(b=>b.onclick=()=>setFit(b.dataset.fit));document.querySelectorAll('#mode button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
  ['zoom','focus-x','focus-y','quality','target-size','background','detail'].forEach(id=>$(id).oninput=()=>{$('zoom-value').textContent=$('zoom').value+'%';$('quality-value').textContent=$('quality').value+'%';$('detail-value').textContent=$('detail').value+'%';schedule();});['format','keep-size'].forEach(id=>$(id).onchange=schedule);$('super-resolution').onchange=()=>{document.querySelector('.upscale-opt').hidden=!$('super-resolution').checked;schedule();};$('target-on').onchange=()=>{document.querySelector('.target-opt').hidden=!$('target-on').checked||exportMode!=='lossy';schedule();};
  $('rotate-left').onclick=()=>{rotation=(rotation+270)%360;schedule();};$('rotate-right').onclick=()=>{rotation=(rotation+90)%360;schedule();};$('flip-x').onclick=()=>{flipX*=-1;schedule();};$('flip-y').onclick=()=>{flipY*=-1;schedule();};
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));schedule();});
  let dragging=false,dragStart=null;$('canvas-wrap').onpointerdown=e=>{if(!current()||fit!=='cover')return;dragging=true;dragStart={x:e.clientX,y:e.clientY,fx:+$('focus-x').value,fy:+$('focus-y').value};$('canvas-wrap').classList.add('dragging');$('canvas-wrap').setPointerCapture(e.pointerId);};$('canvas-wrap').onpointermove=e=>{if(!dragging)return;const r=$('canvas-wrap').getBoundingClientRect(),nx=Math.max(0,Math.min(100,dragStart.fx-(e.clientX-dragStart.x)/r.width*110)),ny=Math.max(0,Math.min(100,dragStart.fy-(e.clientY-dragStart.y)/r.height*110));$('focus-x').value=nx;$('focus-y').value=ny;schedule(true);};$('canvas-wrap').onpointerup=()=>{dragging=false;$('canvas-wrap').classList.remove('dragging');schedule();};
  $('download').onclick=download;$('download-all').onclick=downloadAll;preset();setFit('cover');
})();
