/* PlanetJSON - connected JSON/data toolkit, entirely client-side */
(function () {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const input = $('input'), rightInput = $('right-input'), outCode = $('out-code');
  let mode = 'formatter', lastOutput = '', outputExt = 'txt';
  const MODES = {
    formatter: ['JSON Formatter', 'Pretty-print JSON with syntax highlighting, recursive key sorting and document statistics.', '✨ Format JSON', 'JSON input', 'Formatted JSON'],
    validator: ['JSON Validator', 'Check strict RFC 8259 JSON and locate the first syntax error by line and column.', '✓ Validate JSON', 'JSON input', 'Validation details'],
    minifier: ['JSON Minifier', 'Remove unnecessary whitespace and calculate the exact payload savings.', '▣ Minify JSON', 'JSON input', 'Minified JSON'],
    diff: ['JSON Diff Checker', 'Compare JSON structurally by path, ignoring formatting and object key order.', '⇄ Compare JSON', 'Left JSON', 'Differences'],
    code: ['JSON to Code Models', 'Generate typed, nested data models for popular programming languages from example JSON.', '⌘ Generate models', 'Example JSON', 'Generated code'],
    'json-to-csv': ['JSON to CSV', 'Flatten nested JSON objects into spreadsheet-ready CSV with safe quoted cells.', '▦ Convert to CSV', 'JSON array or object', 'CSV output'],
    'csv-to-json': ['CSV to JSON', 'Parse quoted CSV and optionally rebuild nested objects from dotted column paths.', '{ } Convert to JSON', 'CSV input', 'JSON output']
  };
  const SAMPLE = { users: [{ id: 1, name: 'Ada', active: true, roles: ['admin', 'editor'], address: { city: 'London', zip: 'SW1' } }, { id: 2, name: 'Linus', active: false, roles: ['viewer'], address: { city: 'Helsinki', zip: '00100' } }], meta: { total: 2, generatedAt: '2026-07-10T12:00:00Z' } };

  function bytes(s) { const n = new Blob([s]).size; return n < 1024 ? n + ' B' : n < 1048576 ? (n / 1024).toFixed(1) + ' KB' : (n / 1048576).toFixed(2) + ' MB'; }
  function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
  function highlight(src) { return esc(src).replace(/("(?:\\.|[^"\\])*")(\s*:)?|\b(?:true|false)\b|\bnull\b|-?\b\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b/g, (m, s, colon) => s ? '<span class="' + (colon ? 'tk-key' : 'tk-str') + '">' + s + '</span>' + (colon || '') : '<span class="' + (m === 'true' || m === 'false' ? 'tk-bool' : m === 'null' ? 'tk-null' : 'tk-num') + '">' + m + '</span>'); }
  function status(kind, text) { $('status').className = 'status' + (kind ? ' ' + kind : ''); $('status').textContent = text; }
  function render(text, syntax) { lastOutput = text; outCode.innerHTML = syntax === 'json' ? highlight(text) : esc(text); $('out-stats').textContent = text ? bytes(text) : ''; }
  function indent() { return $('indent-select').value === 'tab' ? '\t' : Number($('indent-select').value); }
  function sortDeep(v) { if (Array.isArray(v)) return v.map(sortDeep); if (v && typeof v === 'object') return Object.keys(v).sort().reduce((o, k) => (o[k] = sortDeep(v[k]), o), {}); return v; }
  function stats(v) { let keys = 0, items = 0, depth = 0; (function walk(x, d) { depth = Math.max(depth, d); if (Array.isArray(x)) { items += x.length; x.forEach(y => walk(y, d + 1)); } else if (x && typeof x === 'object') { const ks = Object.keys(x); keys += ks.length; ks.forEach(k => walk(x[k], d + 1)); } })(v, 1); return { keys, items, depth }; }
  function errorLocation(message, src) { let m = message.match(/line (\d+) column (\d+)/i); if (m) return { line:+m[1], col:+m[2] }; m = message.match(/position (\d+)/i); if (m) { const a = src.slice(0, +m[1]).split('\n'); return { line:a.length, col:a[a.length - 1].length + 1 }; } return null; }
  function parseJSON(src, label) { if (!src.trim()) throw new Error(label + ' is empty.'); try { return JSON.parse(src); } catch (e) { const p = errorLocation(e.message, src); throw new Error('Invalid ' + label + (p ? ' at line ' + p.line + ', column ' + p.col : '') + ': ' + e.message); } }

  function setMode(next) {
    mode = MODES[next] ? next : 'formatter'; const m = MODES[mode];
    $('page-title').textContent = m[0]; $('page-intro').textContent = m[1]; $('btn-run').textContent = m[2]; $('input-label').textContent = m[3]; $('output-label').textContent = m[4];
    document.querySelectorAll('[data-mode]').forEach(a => a.classList.toggle('active', a.dataset.mode === mode));
    document.querySelectorAll('.format-opt').forEach(x => x.hidden = !['formatter','minifier'].includes(mode));
    document.querySelectorAll('.code-opt').forEach(x => x.hidden = mode !== 'code');
    document.querySelectorAll('.csv-opt').forEach(x => x.hidden = mode !== 'csv-to-json');
    $('diff-pane').hidden = mode !== 'diff'; $('editor').classList.toggle('diffing', mode === 'diff');
    input.placeholder = mode === 'csv-to-json' ? 'name,email,address.city\nAda,ada@example.com,London' : '{"paste":"your JSON here"}';
    lastOutput = ''; outCode.textContent = ''; $('out-stats').textContent = ''; outputExt = mode === 'json-to-csv' ? 'csv' : mode === 'code' ? 'txt' : 'json';
    status('', mode === 'diff' ? 'Paste JSON into both panes, then compare.' : m[1]); renderRelated();
  }
  function renderRelated() { const links = Object.entries(MODES).filter(([k]) => k !== mode).slice(0, 4); $('related-links').innerHTML = links.map(([k,v]) => '<a href="#' + k + '">' + v[0].replace('JSON ', '') + '</a>').join(''); }

  function format(minify) { let v = parseJSON(input.value, 'JSON'); if ($('sort-chk').checked) v = sortDeep(v); const text = JSON.stringify(v, null, minify ? 0 : indent()), st = stats(v); render(text, 'json'); outputExt = 'json'; status('ok', minify ? '✓ Minified ' + bytes(input.value) + ' → ' + bytes(text) : '✓ Valid JSON · ' + st.keys + ' keys · ' + st.items + ' array items · depth ' + st.depth); }
  function validateOnly() { const v = parseJSON(input.value, 'JSON'), st = stats(v); const text = ['VALID JSON', '', 'Object keys: ' + st.keys, 'Array items: ' + st.items, 'Maximum depth: ' + st.depth, 'Input size: ' + bytes(input.value), 'Root type: ' + (Array.isArray(v) ? 'array' : v === null ? 'null' : typeof v)].join('\n'); render(text); outputExt = 'txt'; status('ok', '✓ Valid strict JSON (RFC 8259).'); }

  function diffWalk(a, b, path, out) {
    if (Object.is(a, b)) return;
    if (Array.isArray(a) && Array.isArray(b)) { const n = Math.max(a.length, b.length); for (let i=0;i<n;i++) i >= a.length ? out.push(['add', path+'['+i+']', undefined, b[i]]) : i >= b.length ? out.push(['del', path+'['+i+']', a[i], undefined]) : diffWalk(a[i], b[i], path+'['+i+']', out); return; }
    if (a && b && typeof a === 'object' && typeof b === 'object' && !Array.isArray(a) && !Array.isArray(b)) { const keys = new Set([...Object.keys(a), ...Object.keys(b)]); keys.forEach(k => !(k in a) ? out.push(['add', path+'.'+k, undefined, b[k]]) : !(k in b) ? out.push(['del', path+'.'+k, a[k], undefined]) : diffWalk(a[k], b[k], path+'.'+k, out)); return; }
    out.push(['change', path, a, b]);
  }
  function diff() { const a = parseJSON(input.value, 'left JSON'), b = parseJSON(rightInput.value, 'right JSON'), changes = []; diffWalk(a,b,'$',changes); if (!changes.length) { render('No differences. Both JSON values are structurally equal.'); status('ok','✓ No differences found.'); return; } const val = v => JSON.stringify(v); const text = changes.map(x => x[0] === 'add' ? '+ ' + x[1] + ': ' + val(x[3]) : x[0] === 'del' ? '- ' + x[1] + ': ' + val(x[2]) : '~ ' + x[1] + ': ' + val(x[2]) + ' → ' + val(x[3])).join('\n'); render(text); outCode.innerHTML = text.split('\n').map(line => '<span class="diff-' + (line[0] === '+' ? 'add' : line[0] === '-' ? 'del' : 'change') + '">' + esc(line) + '</span>').join('\n'); outputExt='txt'; status('ok','✓ ' + changes.length + ' structural difference' + (changes.length===1?'':'s') + ' found.'); }

  function ident(s, pascal) { let x = String(s).replace(/[^a-zA-Z0-9_$]+(.)?/g, (_,c) => c ? c.toUpperCase() : '').replace(/^[^a-zA-Z_$]+/, ''); if (!x) x='Value'; return pascal ? x[0].toUpperCase()+x.slice(1) : x[0].toLowerCase()+x.slice(1); }
  function mergeSchema(a,b) { if (!a) return b; if (!b) return a; if (a.kind !== b.kind) return {kind:'any'}; if (a.kind==='object') { const fields={...a.fields}; Object.keys(b.fields).forEach(k => fields[k]=mergeSchema(fields[k],b.fields[k])); return {kind:'object',fields}; } if (a.kind==='array') return {kind:'array',item:mergeSchema(a.item,b.item)}; return a; }
  function schema(v, name) { if (v===null) return {kind:'any'}; if (Array.isArray(v)) return {kind:'array',item:v.reduce((s,x)=>mergeSchema(s,schema(x, ident(name,true)+'Item')),null)||{kind:'any'}}; if (typeof v==='object') { const fields={}; Object.keys(v).forEach(k => fields[k]=schema(v[k],ident(k,true))); return {kind:'object',name:ident(name,true),fields}; } return {kind:typeof v==='number'?(Number.isInteger(v)?'integer':'number'):typeof v}; }
  function collectModels(s, name, list, seen) { if (s.kind==='array') return collectModels(s.item,name+'Item',list,seen); if (s.kind!=='object') return; s.name=ident(s.name||name,true); Object.entries(s.fields).forEach(([k,v]) => { if(v.kind==='object'){v.name=ident(k,true);collectModels(v,v.name,list,seen);} else if(v.kind==='array'&&v.item.kind==='object'){v.item.name=ident(k,true)+'Item';collectModels(v.item,v.item.name,list,seen);} }); if(!seen.has(s.name)){seen.add(s.name);list.push(s);} }
  function typeOf(s, lang) { const map={typescript:{string:'string',integer:'number',number:'number',boolean:'boolean',any:'unknown'},csharp:{string:'string',integer:'long',number:'double',boolean:'bool',any:'object'},java:{string:'String',integer:'long',number:'double',boolean:'boolean',any:'Object'},kotlin:{string:'String',integer:'Long',number:'Double',boolean:'Boolean',any:'Any?'},swift:{string:'String',integer:'Int',number:'Double',boolean:'Bool',any:'AnyCodable'},go:{string:'string',integer:'int64',number:'float64',boolean:'bool',any:'any'},rust:{string:'String',integer:'i64',number:'f64',boolean:'bool',any:'serde_json::Value'},python:{string:'str',integer:'int',number:'float',boolean:'bool',any:'Any'},dart:{string:'String',integer:'int',number:'double',boolean:'bool',any:'dynamic'}}[lang]||{}; if(s.kind==='object')return s.name;if(s.kind==='array'){const t=typeOf(s.item,lang);return lang==='typescript'?t+'[]':lang==='csharp'?'List<'+t+'>':lang==='java'||lang==='kotlin'?'List<'+t+'>':lang==='swift'?'['+t+']':lang==='go'?'[]'+t:lang==='rust'?'Vec<'+t+'>':lang==='python'?'list['+t+']':lang==='dart'?'List<'+t+'>':'Array';}return map[s.kind]||'any'; }
  function generateModels(value, lang, root) {
    let s=schema(value,root); if(s.kind==='array'&&s.item.kind==='object'){s.item.name=ident(root,true);s=s.item;} else if(s.kind!=='object') s={kind:'object',name:ident(root,true),fields:{value:s}}; else s.name=ident(root,true);
    const models=[]; collectModels(s,s.name,models,new Set());
    if(lang==='typescript') return models.map(m=>'export interface '+m.name+' {\n'+Object.entries(m.fields).map(([k,v])=>'  '+JSON.stringify(k).replace(/"/g,'')+': '+typeOf(v,lang)+';').join('\n')+'\n}').join('\n\n');
    if(lang==='csharp') return 'using System.Collections.Generic;\nusing System.Text.Json.Serialization;\n\n'+models.map(m=>'public class '+m.name+'\n{\n'+Object.entries(m.fields).map(([k,v])=>'    [JsonPropertyName("'+k+'")]\n    public '+typeOf(v,lang)+' '+ident(k,true)+' { get; set; }').join('\n\n')+'\n}').join('\n\n');
    if(lang==='java') return 'import java.util.List;\nimport com.fasterxml.jackson.annotation.JsonProperty;\n\n'+models.map(m=>'public class '+m.name+' {\n'+Object.entries(m.fields).map(([k,v])=>'    @JsonProperty("'+k+'")\n    private '+typeOf(v,lang)+' '+ident(k,false)+';').join('\n\n')+'\n}').join('\n\n');
    if(lang==='kotlin') return 'import kotlinx.serialization.SerialName\nimport kotlinx.serialization.Serializable\n\n'+models.map(m=>'@Serializable\ndata class '+m.name+'(\n'+Object.entries(m.fields).map(([k,v])=>'    @SerialName("'+k+'") val '+ident(k,false)+': '+typeOf(v,lang)).join(',\n')+'\n)').join('\n\n');
    if(lang==='swift') return models.map(m=>'struct '+m.name+': Codable {\n'+Object.entries(m.fields).map(([k,v])=>'    let '+ident(k,false)+': '+typeOf(v,lang)).join('\n')+'\n}').join('\n\n');
    if(lang==='go') return 'package models\n\n'+models.map(m=>'type '+m.name+' struct {\n'+Object.entries(m.fields).map(([k,v])=>'\t'+ident(k,true)+' '+typeOf(v,lang)+' `json:"'+k+'"`').join('\n')+'\n}').join('\n\n');
    if(lang==='rust') return 'use serde::{Deserialize, Serialize};\n\n'+models.map(m=>'#[derive(Debug, Serialize, Deserialize)]\npub struct '+m.name+' {\n'+Object.entries(m.fields).map(([k,v])=>'    #[serde(rename = "'+k+'")]\n    pub '+ident(k,false)+': '+typeOf(v,lang)+',').join('\n')+'\n}').join('\n\n');
    if(lang==='python') return 'from dataclasses import dataclass\nfrom typing import Any\n\n'+models.map(m=>'@dataclass\nclass '+m.name+':\n'+(Object.keys(m.fields).length?Object.entries(m.fields).map(([k,v])=>'    '+ident(k,false)+': '+typeOf(v,lang)).join('\n'):'    pass')).join('\n\n');
    if(lang==='javascript') return models.map(m=>'/**\n * @typedef {Object} '+m.name+'\n'+Object.entries(m.fields).map(([k,v])=>' * @property {'+(v.kind==='array'?'Array':v.kind==='integer'||v.kind==='number'?'number':v.kind==='object'?v.name:v.kind==='any'?'*':v.kind)+'} '+k).join('\n')+'\n */').join('\n\n');
    if(lang==='php') return '<?php\n\n'+models.map(m=>'final class '+m.name+'\n{\n    public function __construct(\n'+Object.entries(m.fields).map(([k,v])=>'        public mixed $'+ident(k,false)).join(',\n')+'\n    ) {}\n}').join('\n\n');
    if(lang==='dart') return models.map(m=>'class '+m.name+' {\n'+Object.entries(m.fields).map(([k,v])=>'  final '+typeOf(v,lang)+' '+ident(k,false)+';').join('\n')+'\n\n  const '+m.name+'({'+Object.keys(m.fields).map(k=>'required this.'+ident(k,false)).join(', ')+'});\n}').join('\n\n');
    return models.map(m=>'class '+m.name+'\n  attr_accessor '+Object.keys(m.fields).map(k=>':'+ident(k,false)).join(', ')+'\nend').join('\n\n');
  }
  function code() { const v=parseJSON(input.value,'JSON'), lang=$('language').value, root=ident($('root-name').value||'Root',true), text=generateModels(v,lang,root); render(text); outputExt=({typescript:'ts',csharp:'cs',java:'java',kotlin:'kt',swift:'swift',go:'go',rust:'rs',python:'py',javascript:'js',php:'php',dart:'dart',ruby:'rb'})[lang]; status('ok','✓ Generated '+text.split('\n').filter(x=>/^(export interface|public class|data class|struct |type |pub struct|class )/.test(x)).length+' nested model(s) for '+$('language').selectedOptions[0].text+'.'); }

  function flatten(obj,prefix,out){out=out||{};prefix=prefix||'';Object.entries(obj||{}).forEach(([k,v])=>{const p=prefix?prefix+'.'+k:k;if(v&&typeof v==='object'&&!Array.isArray(v))flatten(v,p,out);else out[p]=v;});return out;}
  function csvCell(v){if(v===null||v===undefined)return '';const s=typeof v==='object'?JSON.stringify(v):String(v);return /[",\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
  function jsonToCsv(){let v=parseJSON(input.value,'JSON');let rows=Array.isArray(v)?v:[v];if(!rows.every(x=>x&&typeof x==='object'&&!Array.isArray(x)))throw new Error('JSON must be an object or an array of objects.');rows=rows.map(x=>flatten(x));const headers=[...new Set(rows.flatMap(Object.keys))];const text=[headers.map(csvCell).join(','),...rows.map(r=>headers.map(h=>csvCell(r[h])).join(','))].join('\r\n');render(text);outputExt='csv';status('ok','✓ Converted '+rows.length+' row(s) and '+headers.length+' column(s) to CSV.');}
  function parseCsv(src){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<src.length;i++){const c=src[i];if(quoted){if(c==='"'&&src[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=false;else cell+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell='';}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}if(quoted)throw new Error('CSV contains an unclosed quoted field.');return rows;}
  function autoValue(s){const t=s.trim();if(t==='')return '';if(t==='true')return true;if(t==='false')return false;if(t==='null')return null;if(/^-?\d+(\.\d+)?$/.test(t))return Number(t);if((t[0]==='['&&t.endsWith(']'))||(t[0]==='{'&&t.endsWith('}')))try{return JSON.parse(t);}catch(_){}return s;}
  function setPath(obj,path,val){const parts=path.split('.');let cur=obj;parts.forEach((p,i)=>{if(i===parts.length-1)cur[p]=val;else cur=cur[p]||(cur[p]={});});}
  function csvToJson(){const rows=parseCsv(input.value);if(rows.length<1)throw new Error('CSV input is empty.');const headers=rows.shift().map(x=>x.trim());if(new Set(headers).size!==headers.length)throw new Error('CSV headers must be unique.');const result=rows.filter(r=>r.some(Boolean)).map(r=>{const o={};headers.forEach((h,i)=>$('nested-chk').checked?setPath(o,h,autoValue(r[i]||'')):o[h]=autoValue(r[i]||''));return o;});const text=JSON.stringify(result,null,indent());render(text,'json');outputExt='json';status('ok','✓ Converted '+result.length+' CSV row(s) to JSON.');}

  function run(){try{if(mode==='formatter')format(false);else if(mode==='validator')validateOnly();else if(mode==='minifier')format(true);else if(mode==='diff')diff();else if(mode==='code')code();else if(mode==='json-to-csv')jsonToCsv();else csvToJson();}catch(e){status('err','✗ '+e.message);}}
  $('btn-run').onclick=run; $('language').onchange=()=>{if(input.value.trim())run();};
  $('btn-copy').onclick=async()=>{if(!lastOutput)return status('err','✗ Nothing to copy yet.');try{await navigator.clipboard.writeText(lastOutput);status('ok','✓ Copied '+bytes(lastOutput)+' to the clipboard.');}catch(_){status('err','✗ Clipboard access was blocked.');}};
  $('btn-download').onclick=()=>{if(!lastOutput)return status('err','✗ Nothing to download yet.');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lastOutput],{type:outputExt==='csv'?'text/csv':'text/plain'}));a.download='fastjson-output.'+outputExt;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);};
  $('btn-open').onclick=()=>$('file-input').click();$('file-input').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{input.value=String(r.result);run();};r.readAsText(f);e.target.value='';};
  $('btn-clear').onclick=()=>{input.value='';rightInput.value='';lastOutput='';outCode.textContent='';$('in-stats').textContent=$('right-stats').textContent=$('out-stats').textContent='';status('',MODES[mode][1]);};
  $('btn-sample').onclick=()=>{if(mode==='csv-to-json')input.value='id,name,active,address.city,roles\n1,Ada,true,London,"[""admin"",""editor""]"\n2,Linus,false,Helsinki,"[""viewer""]"';else input.value=JSON.stringify(mode==='json-to-csv'?SAMPLE.users:SAMPLE,null,2);if(mode==='diff')rightInput.value=JSON.stringify({...SAMPLE,meta:{...SAMPLE.meta,total:3}},null,2);run();};
  let timer;[input,rightInput].forEach(el=>el.addEventListener('input',()=>{el===input?$('in-stats').textContent=bytes(el.value):$('right-stats').textContent=bytes(el.value);if(mode==='validator'){clearTimeout(timer);timer=setTimeout(run,250);}}));
  addEventListener('hashchange',()=>setMode(location.hash.slice(1)));setMode(location.hash.slice(1)||'formatter');
})();
